// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit_logs.sql

package repository

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const cleanOldAuditLogs = `-- name: CleanOldAuditLogs :exec
delete from audit_logs
where created_at < $1
`

func (q *Queries) CleanOldAuditLogs(ctx context.Context, createdAt sql.NullTime) error {
	_, err := q.db.ExecContext(ctx, cleanOldAuditLogs, createdAt)
	return err
}

const createAuditLog = `-- name: CreateAuditLog :one
insert into audit_logs (user_id, event_type, ip, ua, payload)
values ($1, $2, $3, $4, $5)
returning id, user_id, event_type, ip, ua, payload, created_at
`

type CreateAuditLogParams struct {
	UserID    uuid.NullUUID
	EventType string
	Ip        pqtype.Inet
	Ua        sql.NullString
	Payload   pqtype.NullRawMessage
}

func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error) {
	row := q.db.QueryRowContext(ctx, createAuditLog,
		arg.UserID,
		arg.EventType,
		arg.Ip,
		arg.Ua,
		arg.Payload,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EventType,
		&i.Ip,
		&i.Ua,
		&i.Payload,
		&i.CreatedAt,
	)
	return i, err
}

const getAuditLogsByEventType = `-- name: GetAuditLogsByEventType :many
select id, user_id, event_type, ip, ua, payload, created_at
from audit_logs
where event_type = $1
order by created_at desc
limit $2 offset $3
`

type GetAuditLogsByEventTypeParams struct {
	EventType string
	Limit     int32
	Offset    int32
}

func (q *Queries) GetAuditLogsByEventType(ctx context.Context, arg GetAuditLogsByEventTypeParams) ([]AuditLog, error) {
	rows, err := q.db.QueryContext(ctx, getAuditLogsByEventType, arg.EventType, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.EventType,
			&i.Ip,
			&i.Ua,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAuditLogsByUser = `-- name: GetAuditLogsByUser :many
select id, user_id, event_type, ip, ua, payload, created_at
from audit_logs
where user_id = $1
order by created_at desc
limit $2 offset $3
`

type GetAuditLogsByUserParams struct {
	UserID uuid.NullUUID
	Limit  int32
	Offset int32
}

func (q *Queries) GetAuditLogsByUser(ctx context.Context, arg GetAuditLogsByUserParams) ([]AuditLog, error) {
	rows, err := q.db.QueryContext(ctx, getAuditLogsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.EventType,
			&i.Ip,
			&i.Ua,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentAuditLogs = `-- name: GetRecentAuditLogs :many
select id, user_id, event_type, ip, ua, payload, created_at
from audit_logs
order by created_at desc
limit $1 offset $2
`

type GetRecentAuditLogsParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) GetRecentAuditLogs(ctx context.Context, arg GetRecentAuditLogsParams) ([]AuditLog, error) {
	rows, err := q.db.QueryContext(ctx, getRecentAuditLogs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.EventType,
			&i.Ip,
			&i.Ua,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
