// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: email_verification.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const cleanExpiredEmailVerificationTokens = `-- name: CleanExpiredEmailVerificationTokens :exec
delete from email_verification_tokens
where expires_at < now()
`

func (q *Queries) CleanExpiredEmailVerificationTokens(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, cleanExpiredEmailVerificationTokens)
	return err
}

const createEmailVerificationToken = `-- name: CreateEmailVerificationToken :one
insert into email_verification_tokens (user_id, token_hash, expires_at)
values ($1, $2, $3)
returning id, user_id, token_hash, expires_at, used_at, created_at
`

type CreateEmailVerificationTokenParams struct {
	UserID    uuid.NullUUID
	TokenHash string
	ExpiresAt time.Time
}

func (q *Queries) CreateEmailVerificationToken(ctx context.Context, arg CreateEmailVerificationTokenParams) (EmailVerificationToken, error) {
	row := q.db.QueryRowContext(ctx, createEmailVerificationToken, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	var i EmailVerificationToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getEmailVerificationToken = `-- name: GetEmailVerificationToken :one
select id, user_id, token_hash, expires_at, used_at, created_at
from email_verification_tokens
where id = $1
    and used_at is null
    and expires_at > now()
`

func (q *Queries) GetEmailVerificationToken(ctx context.Context, id uuid.UUID) (EmailVerificationToken, error) {
	row := q.db.QueryRowContext(ctx, getEmailVerificationToken, id)
	var i EmailVerificationToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getEmailVerificationTokenByHash = `-- name: GetEmailVerificationTokenByHash :one
select id, user_id, token_hash, expires_at, used_at, created_at
from email_verification_tokens
where token_hash = $1
    and used_at is null
    and expires_at > now()
`

func (q *Queries) GetEmailVerificationTokenByHash(ctx context.Context, tokenHash string) (EmailVerificationToken, error) {
	row := q.db.QueryRowContext(ctx, getEmailVerificationTokenByHash, tokenHash)
	var i EmailVerificationToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const markEmailVerificationTokenUsed = `-- name: MarkEmailVerificationTokenUsed :exec
update email_verification_tokens
set used_at = now()
where id = $1
`

func (q *Queries) MarkEmailVerificationTokenUsed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, markEmailVerificationTokenUsed, id)
	return err
}
