// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type AuditLog struct {
	ID        uuid.UUID
	UserID    uuid.NullUUID
	EventType string
	Ip        pqtype.Inet
	Ua        sql.NullString
	Payload   pqtype.NullRawMessage
	CreatedAt sql.NullTime
}

type EmailVerificationToken struct {
	ID        uuid.UUID
	UserID    uuid.NullUUID
	TokenHash string
	ExpiresAt time.Time
	UsedAt    sql.NullTime
	CreatedAt sql.NullTime
}

type PasswordResetToken struct {
	ID        uuid.UUID
	UserID    uuid.NullUUID
	TokenHash string
	ExpiresAt time.Time
	UsedAt    sql.NullTime
	CreatedAt sql.NullTime
}

type RefreshToken struct {
	ID          uuid.UUID
	UserID      uuid.NullUUID
	DeviceInfo  sql.NullString
	RotatedFrom uuid.NullUUID
	Revoked     sql.NullBool
	CreatedAt   sql.NullTime
	ExpiresAt   time.Time
	LastUsedAt  sql.NullTime
}

type User struct {
	ID             uuid.UUID
	Email          string
	PasswordHash   string
	Permissions    int64
	IsActive       sql.NullBool
	EmailConfirmed sql.NullBool
	CreatedAt      sql.NullTime
	UpdatedAt      sql.NullTime
}
