// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: password_reset.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const cleanExpiredPasswordResetTokens = `-- name: CleanExpiredPasswordResetTokens :exec
delete from password_reset_tokens
where expires_at < now()
`

func (q *Queries) CleanExpiredPasswordResetTokens(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, cleanExpiredPasswordResetTokens)
	return err
}

const createPasswordResetToken = `-- name: CreatePasswordResetToken :one
insert into password_reset_tokens (user_id, token_hash, expires_at)
values ($1, $2, $3)
returning id, user_id, token_hash, expires_at, used_at, created_at
`

type CreatePasswordResetTokenParams struct {
	UserID    uuid.NullUUID
	TokenHash string
	ExpiresAt time.Time
}

func (q *Queries) CreatePasswordResetToken(ctx context.Context, arg CreatePasswordResetTokenParams) (PasswordResetToken, error) {
	row := q.db.QueryRowContext(ctx, createPasswordResetToken, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	var i PasswordResetToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getPasswordResetToken = `-- name: GetPasswordResetToken :one
select id, user_id, token_hash, expires_at, used_at, created_at
from password_reset_tokens
where id = $1
    and used_at is null
    and expires_at > now()
`

func (q *Queries) GetPasswordResetToken(ctx context.Context, id uuid.UUID) (PasswordResetToken, error) {
	row := q.db.QueryRowContext(ctx, getPasswordResetToken, id)
	var i PasswordResetToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getPasswordResetTokenByHash = `-- name: GetPasswordResetTokenByHash :one
select id, user_id, token_hash, expires_at, used_at, created_at
from password_reset_tokens
where token_hash = $1
    and used_at is null
    and expires_at > now()
`

func (q *Queries) GetPasswordResetTokenByHash(ctx context.Context, tokenHash string) (PasswordResetToken, error) {
	row := q.db.QueryRowContext(ctx, getPasswordResetTokenByHash, tokenHash)
	var i PasswordResetToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const markPasswordResetTokenUsed = `-- name: MarkPasswordResetTokenUsed :exec
update password_reset_tokens
set used_at = now()
where id = $1
`

func (q *Queries) MarkPasswordResetTokenUsed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, markPasswordResetTokenUsed, id)
	return err
}
