// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CleanExpiredEmailVerificationTokens(ctx context.Context) error
	CleanExpiredPasswordResetTokens(ctx context.Context) error
	CleanExpiredTokens(ctx context.Context) error
	CleanOldAuditLogs(ctx context.Context, createdAt pgtype.Timestamptz) error
	CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error)
	CreateEmailVerificationToken(ctx context.Context, arg CreateEmailVerificationTokenParams) (EmailVerificationToken, error)
	CreatePasswordResetToken(ctx context.Context, arg CreatePasswordResetTokenParams) (PasswordResetToken, error)
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetAuditLogsByEventType(ctx context.Context, arg GetAuditLogsByEventTypeParams) ([]AuditLog, error)
	GetAuditLogsByUser(ctx context.Context, arg GetAuditLogsByUserParams) ([]AuditLog, error)
	GetEmailVerificationToken(ctx context.Context, id pgtype.UUID) (EmailVerificationToken, error)
	GetEmailVerificationTokenByHash(ctx context.Context, tokenHash string) (EmailVerificationToken, error)
	GetPasswordResetToken(ctx context.Context, id pgtype.UUID) (PasswordResetToken, error)
	GetPasswordResetTokenByHash(ctx context.Context, tokenHash string) (PasswordResetToken, error)
	GetRecentAuditLogs(ctx context.Context, arg GetRecentAuditLogsParams) ([]AuditLog, error)
	GetRefreshToken(ctx context.Context, id pgtype.UUID) (RefreshToken, error)
	GetUserActiveTokens(ctx context.Context, userID pgtype.UUID) ([]RefreshToken, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	MarkEmailVerificationTokenUsed(ctx context.Context, id pgtype.UUID) error
	MarkPasswordResetTokenUsed(ctx context.Context, id pgtype.UUID) error
	RevokeAllUserTokens(ctx context.Context, userID pgtype.UUID) error
	RevokeRefreshToken(ctx context.Context, id pgtype.UUID) error
	RevokeTokenFamily(ctx context.Context, id pgtype.UUID) error
	UpdateRefreshTokenLastUsed(ctx context.Context, id pgtype.UUID) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (User, error)
	UpdateUserPermissions(ctx context.Context, arg UpdateUserPermissionsParams) (User, error)
}

var _ Querier = (*Queries)(nil)
