// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
insert into users (email, password_hash, permissions)
values ($1, $2, $3)
returning id, email, password_hash, permissions, is_active, email_confirmed, created_at, updated_at
`

type CreateUserParams struct {
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
	Permissions  int64  `json:"permissions"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.PasswordHash, arg.Permissions)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Permissions,
		&i.IsActive,
		&i.EmailConfirmed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
select id, email, password_hash, permissions, is_active, email_confirmed, created_at, updated_at
from users
where email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Permissions,
		&i.IsActive,
		&i.EmailConfirmed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
select id, email, password_hash, permissions, is_active, email_confirmed, created_at, updated_at
from users
where id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Permissions,
		&i.IsActive,
		&i.EmailConfirmed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
update users
set email = coalesce(nullif($2, ''), email),
    password_hash = coalesce(nullif($3, ''), password_hash),
    permissions = coalesce($4, permissions),
    is_active = coalesce($5, is_active),
    email_confirmed = coalesce($6, email_confirmed)
where id = $1
returning id, email, password_hash, permissions, is_active, email_confirmed, created_at, updated_at
`

type UpdateUserParams struct {
	ID             pgtype.UUID `json:"id"`
	Column2        interface{} `json:"column_2"`
	Column3        interface{} `json:"column_3"`
	Permissions    int64       `json:"permissions"`
	IsActive       pgtype.Bool `json:"is_active"`
	EmailConfirmed pgtype.Bool `json:"email_confirmed"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.Column2,
		arg.Column3,
		arg.Permissions,
		arg.IsActive,
		arg.EmailConfirmed,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Permissions,
		&i.IsActive,
		&i.EmailConfirmed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :one
update users
set password_hash = $2,
    updated_at = now()
where id = $1
returning id, email, password_hash, permissions, is_active, email_confirmed, created_at, updated_at
`

type UpdateUserPasswordParams struct {
	ID           pgtype.UUID `json:"id"`
	PasswordHash string      `json:"password_hash"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserPassword, arg.ID, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Permissions,
		&i.IsActive,
		&i.EmailConfirmed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserPermissions = `-- name: UpdateUserPermissions :one
update users
set permissions = $2
where id = $1
returning id, email, password_hash, permissions, is_active, email_confirmed, created_at, updated_at
`

type UpdateUserPermissionsParams struct {
	ID          pgtype.UUID `json:"id"`
	Permissions int64       `json:"permissions"`
}

func (q *Queries) UpdateUserPermissions(ctx context.Context, arg UpdateUserPermissionsParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserPermissions, arg.ID, arg.Permissions)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Permissions,
		&i.IsActive,
		&i.EmailConfirmed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
