// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package repository

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
insert into users (email, password_hash, permissions)
values ($1, $2, $3)
returning id, email, password_hash, permissions, is_active, email_confirmed, created_at, updated_at
`

type CreateUserParams struct {
	Email        string
	PasswordHash string
	Permissions  int64
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Email, arg.PasswordHash, arg.Permissions)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Permissions,
		&i.IsActive,
		&i.EmailConfirmed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
select id, email, password_hash, permissions, is_active, email_confirmed, created_at, updated_at
from users
where email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Permissions,
		&i.IsActive,
		&i.EmailConfirmed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
select id, email, password_hash, permissions, is_active, email_confirmed, created_at, updated_at
from users
where id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Permissions,
		&i.IsActive,
		&i.EmailConfirmed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
update users
set email = coalesce($2, email),
    password_hash = coalesce($3, password_hash),
    permissions = coalesce($4, permissions),
    is_active = coalesce($5, is_active),
    email_confirmed = coalesce($6, email_confirmed)
where id = $1
returning id, email, password_hash, permissions, is_active, email_confirmed, created_at, updated_at
`

type UpdateUserParams struct {
	ID             uuid.UUID
	Email          string
	PasswordHash   string
	Permissions    int64
	IsActive       sql.NullBool
	EmailConfirmed sql.NullBool
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUser,
		arg.ID,
		arg.Email,
		arg.PasswordHash,
		arg.Permissions,
		arg.IsActive,
		arg.EmailConfirmed,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Permissions,
		&i.IsActive,
		&i.EmailConfirmed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserPermissions = `-- name: UpdateUserPermissions :one
update users
set permissions = $2
where id = $1
returning id, email, password_hash, permissions, is_active, email_confirmed, created_at, updated_at
`

type UpdateUserPermissionsParams struct {
	ID          uuid.UUID
	Permissions int64
}

func (q *Queries) UpdateUserPermissions(ctx context.Context, arg UpdateUserPermissionsParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserPermissions, arg.ID, arg.Permissions)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Permissions,
		&i.IsActive,
		&i.EmailConfirmed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
