package constants

const (
	ENV                  = "ENV"
	DB_CONN              = "DB_CONN"
	PORT                 = "PORT"
	DEVELOPMENT          = "development"
	REDIS_HOST           = "REDIS_HOST"
	REDIS_PORT           = "REDIS_PORT"
	REDIS_PASSWORD       = "REDIS_PASSWORD"
	JWT_ACCESS_SECRET    = "JWT_ACCESS_SECRET"
	JWT_REFRESH_SECRET   = "JWT_REFRESH_SECRET"
	APP_URL              = "APP_URL"
	SMTP_HOST            = "SMTP_HOST"
	SMTP_PORT            = "SMTP_PORT"
	SMTP_FROM            = "SMTP_FROM"
	SMTP_PASSWORD        = "SMTP_PASSWORD"
	SMTP_USER            = "SMTP_USER"
	GRPC_PORT            = "GRPC_PORT"
	GRPC_TLS_ENABLED     = "GRPC_TLS_ENABLED"
	GRPC_CERT_FILE       = "GRPC_CERT_FILE"
	GRPC_KEY_FILE        = "GRPC_KEY_FILE"
	CORS_ALLOWED_ORIGINS = "CORS_ALLOWED_ORIGINS"
	COOKIE_DOMAIN        = "COOKIE_DOMAIN"
)
